### PR TITLE
README.rst had utf-8 encoding

### PR DESCRIPTION
**Pull request by colbyprior**
Just a small thing. I ran into some issues installing this package in AWS user-data because of the utf-8 encoding in README.rst.

### CODE REVIEW

**Comment by gtback** [comment]
Thanks, @colbyprior ! I was confused at first, thinking "where is the non-ASCII text in the README?" before realizing it's the `™` character. There are a couple build failures, some of which are due to `encoding` not working on Python 2, and others just because of some other legacy stuff (unrelated to this change) that needs to be cleaned up. 

I'll work on getting this all cleaned up and then merge this in! Thanks again.

**Comment by gtback** [comment]
I merged this via the command line. All the tests should pass in `master`.

**Comment by colbyprior** [comment]
Awesome. Thanks for the quick turnaround and fixing up the Python 2 test as-well.

**Comment by gtback** [comment]
Thanks for the contribution, @colbyprior !

**Pull request merged**
