### PR TITLE
Expanded Vocab Implementation

### PR DESCRIPTION
**Pull request by ikiril01**
* Adds Vocab classes a la `python-stix` and `python-stix`
* Updates certain fields with VocabFields w/ default vocabulary classes for better validation of values

### CODE REVIEW

**Comment by bworrell** [comment]
This is gonna keep failing until python-cybox gets updated with all the new `VocabString` and `VocabField` hotness.

In the meantime, if we want to calm Travis down we could alter the `.travis.yml` file to point to `master` of the python-cybox repo, kinda like [**this**](https://github.com/STIXProject/python-stix/commit/c00ea2e36d74985e28a444d0edd73c2e8f269436).

We need to make sure to up the `cybox` dependency version in the python-maec `setup.py` before pushing out the next python-maec release.

**Comment by ikiril01** [comment]
@bworrell yeah, I realize that. I think you're right that Travis will still complain until https://github.com/CybOXProject/python-cybox/pull/245 is merged even if we modify `.travis.yml` to point to `master`. I've done testing on my end with the latest changes in https://github.com/CybOXProject/python-cybox/pull/245, so I'm fine with just ignoring this build error. 

Good point about updating the `cybox` dependency in `setup.py` for the next release; I'll add a tracker item for this.

**Comment by gtback** [comment]
I made some tweaks to how CybOX vocabs work in https://github.com/CybOXProject/python-cybox/commit/57ababaa7f00e1395844a94e11011255433329aa, so I had to adjust some things here. I also fixed a couple other tests that were failing, and found a bug in python-cybox that was causing another test failure here. 

Once I push out a python-cybox release, these tests should all pass and this can get merged in.

**Comment by ikiril01** [comment]
@gtback MalwareCapability is just an enumeration, not a controlled vocabulary. That's why it necessitated the addition of the `EnumString` class.

**Comment by gtback** [comment]
Sorry, @ikiril01, I got rid of `CapabilityName` because it looked like a duplicate of `MalwareCapability`. I didn't realize that one was a vocab and the other was an enum. I still don't think I like implementing EnumString as a separate class, particularly because Capability Name is only being used in an attribute rather than as another element. I was also confused because it was in the `vocabs.py` module :wink:

**Comment by ikiril01** [comment]
@gtback No worries. Yeah, I'm not a huge fan of the `EnumString` class either; it's rather klugey and doesn't work in a TypedField anyway in its current state (since _objectify/etc. doesn't call it's to_dict()/to_obj() methods). I think I'll just get rid of it and do the @name value checking in the Capability class.

**Comment by ikiril01** [comment]
This looks good to me now - merging! :)

**Pull request merged**
